### ISSUE TITLE
value error while running 'raasa train'

### ISSUE THREAD

**Issue by khegde22** [RasaHQ/tutorial-rasa-google-assistant#10]
ValueError: Found markdown section 'itent' which is not in the allowed sections 'intent', 'synonym', 'regex', 'lookup'. >> i am getting this error while i am running 'rasa train'.

Complete error :

/home/karthik/anaconda3/envs/rasa-google/lib/python3.7/site-packages/rasa/core/domain.py:154: FutureWarning: No tracker session configuration was found in the loaded domain. Domains without a session config will automatically receive a session expiration time of 60 minutes in Rasa version 2.0 if not configured otherwise.
  FutureWarning,
Traceback (most recent call last):
  File "/home/karthik/anaconda3/envs/rasa-google/bin/rasa", line 8, in <module>
    sys.exit(main())
  File "/home/karthik/anaconda3/envs/rasa-google/lib/python3.7/site-packages/rasa/__main__.py", line 76, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/home/karthik/anaconda3/envs/rasa-google/lib/python3.7/site-packages/rasa/cli/train.py", line 76, in train
    kwargs=extract_additional_arguments(args),
  File "/home/karthik/anaconda3/envs/rasa-google/lib/python3.7/site-packages/rasa/train.py", line 46, in train
    kwargs=kwargs,
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/home/karthik/anaconda3/envs/rasa-google/lib/python3.7/site-packages/rasa/train.py", line 97, in train_async
    kwargs,
  File "/home/karthik/anaconda3/envs/rasa-google/lib/python3.7/site-packages/rasa/train.py", line 140, in _train_async_internal
    file_importer.get_stories(), file_importer.get_nlu_data()
  File "/home/karthik/anaconda3/envs/rasa-google/lib/python3.7/site-packages/rasa/importers/importer.py", line 269, in get_nlu_data
    nlu_data = await asyncio.gather(*nlu_data)
  File "/home/karthik/anaconda3/envs/rasa-google/lib/python3.7/site-packages/rasa/importers/rasa.py", line 61, in get_nlu_data
    return utils.training_data_from_paths(self._nlu_files, language)
  File "/home/karthik/anaconda3/envs/rasa-google/lib/python3.7/site-packages/rasa/importers/utils.py", line 9, in training_data_from_paths
    training_datas = [loading.load_data(nlu_file, language) for nlu_file in paths]
  File "/home/karthik/anaconda3/envs/rasa-google/lib/python3.7/site-packages/rasa/importers/utils.py", line 9, in <listcomp>
    training_datas = [loading.load_data(nlu_file, language) for nlu_file in paths]
  File "/home/karthik/anaconda3/envs/rasa-google/lib/python3.7/site-packages/rasa/nlu/training_data/loading.py", line 67, in load_data
    data_sets = [_load(f, language) for f in files]
  File "/home/karthik/anaconda3/envs/rasa-google/lib/python3.7/site-packages/rasa/nlu/training_data/loading.py", line 67, in <listcomp>
    data_sets = [_load(f, language) for f in files]
  File "/home/karthik/anaconda3/envs/rasa-google/lib/python3.7/site-packages/rasa/nlu/training_data/loading.py", line 138, in _load
    return reader.read(filename, language=language, fformat=fformat)
  File "/home/karthik/anaconda3/envs/rasa-google/lib/python3.7/site-packages/rasa/nlu/training_data/formats/readerwriter.py", line 15, in read
    return self.reads(rasa.utils.io.read_file(filename), **kwargs)
  File "/home/karthik/anaconda3/envs/rasa-google/lib/python3.7/site-packages/rasa/nlu/training_data/formats/markdown.py", line 76, in reads
    self._set_current_section(header[0], header[1])
  File "/home/karthik/anaconda3/envs/rasa-google/lib/python3.7/site-packages/rasa/nlu/training_data/formats/markdown.py", line 195, in _set_current_section
    "".format(section, "', '".join(available_sections))
ValueError: Found markdown section 'itent' which is not in the allowed sections 'intent', 'synonym', 'regex', 'lookup'.

********
I tried with both python 3.6.8 version and python 3.7.3 version, same error getting in both the cases
Also, i haven't modified any of the data files(nlu.md or stories.md)

Please assist..

**Comment by khegde22** [comment]
There is a small typo in the nlu_data.md file Instead of 'intent' , 'itent' has written.
